package game


val MIN_Y = 0
val MAX_Y = 500
val MIN_X = 0
val MAX_X = 1000
val PLAYER_VEL = 2
val PLAYER_SIZE = 50
val FOODBOX_SIZE = 50
val TABLE_HEIGHT = 600
val TABLE_WIDTH = 400
val TABLE_POS = Pos(MAX_X/2- TABLE_WIDTH/2, MIN_Y/2-MAX_Y-PLAYER_SIZE*2)