import pygame as pg

DEFAULT_FONT = pg.font.Font(None, 64)

PLAYER_NAME_FONT_SIZE = 20
PLAYER_NAME_FONT = pg.font.Font(None, PLAYER_NAME_FONT_SIZE)
PLAYER_NAME_FONT.set_italic(False)
PLAYER_NAME_FONT.set_bold(True)
PLAYER_NAME_FONT_COLOR = (255, 50, 50)

TIMER_FONT_SIZE = 36

POPUP_FONT_SIZE = 32

RECIPE_FONT_SIZE = 32
RECIPE_FONT_COLOR = (12, 12, 12)
RECIPE_NAME_FONT = pg.font.Font(None, RECIPE_FONT_SIZE)
RECIPE_NAME_FONT.set_italic(True)

INGREDIENT_FONT_COLOR = (30, 30, 30)
INGREDIENT_FONT_SIZE = 22
INGREDIENT_FONT = pg.font.Font(None, INGREDIENT_FONT_SIZE)

TIMER_FONT = pg.font.Font(None, TIMER_FONT_SIZE)
POPUP_FONT = pg.font.Font(None, POPUP_FONT_SIZE)


